name: soqya
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: any
  http:
  shared_preferences:
  splashscreen:
  connectivity:
  liquid_pull_to_refresh:
  url_launcher:
  carousel_slider: ^1.4.1
  fluttertoast: ^7.0.4
  provider: ^4.3.2+2
  firebase_messaging: ^7.0.0
  firebase_core: ^0.5.0

  drawerbehavior:
  progress_button:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: GE_Dinar_One_Light
      fonts:
        - asset: assets/GE_Dinar_One_Light.otf
    - family: GE-Dinar_One_Medium
      fonts:
        - asset: assets/GE_Dinar_One_Medium.otf
    - family: Mj_Dinar_Two_Light
      fonts:
        - asset: assets/Mj_Dinar_Two_Light.ttf
    - family: lemonada_bold
      fonts:
        - asset: assets/lemonada_bold.ttf
